# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-29 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kursus', models.CharField(max_length=50)),
                ('slbkursus', models.TextField(default=True)),
                ('semester', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul', models.CharField(max_length=50)),
                ('slbmatkul', models.TextField(default=True)),
                ('semester', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesi', models.CharField(max_length=50)),
                ('unitk', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfKursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesi', models.CharField(max_length=50)),
                ('kursus', models.CharField(max_length=50)),
                ('presentase', models.CharField(max_length=4)),
                ('katasama', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfMatkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesi', models.CharField(max_length=50)),
                ('matkul', models.CharField(max_length=50)),
                ('presentase', models.CharField(max_length=4)),
                ('katasama', models.TextField(default=True)),
            ],
        ),
    ]
